(function () {
  var defaults={canvasWidth:1000,canvasHeight:1000,resolutionDpi:300,backgroundColor:'#FFFFFF',backgroundTransparent:false,patternType:'circle',patternColor:'#F7C7D5',patternSize:30,gapX:35,gapY:35,patternAngle:0,patternOpacity:100,patternBlur:0,offsetX:0,offsetY:0,customImage:null,background:null,stickers:[],erased:{}};
  var state=Object.assign({},defaults), canvas=document.getElementById('previewCanvas'), stage=document.getElementById('canvasStage'), badge=document.getElementById('canvasBadge'), raf=0, ratio=1, toastTimer, dragState=null;
  function clampNumber(value,min,max,fallback){value=Number(value);return Number.isFinite(value)?Math.max(min,Math.min(max,value)):fallback;}
  function showToast(message){var toast=document.getElementById('toast');toast.textContent='✦ '+message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){toast.classList.remove('show');},2800);}
  function scheduleRender(){cancelAnimationFrame(raf);raf=requestAnimationFrame(render);}
  function render(){var rect=stage.getBoundingClientRect(), maxW=Math.max(120,rect.width-36), maxH=Math.max(120,rect.height-36), fit=Math.min(maxW/state.canvasWidth,maxH/state.canvasHeight,1), quality=Math.min(1,1100/Math.max(state.canvasWidth,state.canvasHeight)), backing=Math.max(.1,Math.min(fit,quality));canvas.width=Math.max(1,Math.round(state.canvasWidth*backing));canvas.height=Math.max(1,Math.round(state.canvasHeight*backing));canvas.style.width=Math.max(1,Math.round(state.canvasWidth*fit))+'px';canvas.style.height=Math.max(1,Math.round(state.canvasHeight*fit))+'px';window.PatternRenderer.drawPattern(canvas.getContext('2d'),state,state.canvasWidth,state.canvasHeight,backing);badge.textContent=state.canvasWidth+' × '+state.canvasHeight+' px';}
  function connectRange(rangeId,numberId,key,min,max){var range=document.getElementById(rangeId),number=document.getElementById(numberId);function update(value){state[key]=clampNumber(value,min,max,state[key]);range.value=state[key];number.value=state[key];scheduleRender();}range.addEventListener('input',function(){window.Editor&&window.Editor.noteParam();update(range.value);});range.addEventListener('change',function(){window.Editor&&window.Editor.commitParam();});number.addEventListener('input',function(){window.Editor&&window.Editor.noteParam();update(number.value);});number.addEventListener('change',function(){window.Editor&&window.Editor.commitParam();});}
  function syncControlsFromState(){['patternSize','gapX','gapY','patternAngle','patternOpacity','patternBlur'].forEach(function(key){document.getElementById(key).value=state[key];document.getElementById(key+'Range').value=state[key];});connectColorValues('background',state.backgroundColor);connectColorValues('pattern',state.patternColor);syncBackgroundTransparency();}
  function syncBackgroundTransparency(){var checkbox=document.getElementById('backgroundTransparent'),section=document.getElementById('backgroundColorSection');checkbox.checked=state.backgroundTransparent;section.classList.toggle('is-transparent',state.backgroundTransparent);}
  function connectColor(name){var swatch=document.getElementById(name+'Picker'),key=name==='background'?'backgroundColor':'patternColor';swatch.style.background=state[key];swatch.addEventListener('click',function(){if(name==='background'&&state.background){showToast('已使用自定义背景图，背景颜色暂不可用');return;}window.ColorPicker.open(swatch,state[key],function(hex){window.Editor&&window.Editor.noteParam();state[key]=hex;if(name==='background'&&state.backgroundTransparent){state.backgroundTransparent=false;syncBackgroundTransparency();}swatch.style.background=hex;scheduleRender();});});}
  function updateCanvasSize(side,commit){if(state.background){return;}var width=document.getElementById('canvasWidth'),height=document.getElementById('canvasHeight'),locked=document.getElementById('lockRatio').checked;var nextWidth=Number(width.value),nextHeight=Number(height.value);if(!Number.isFinite(nextWidth)||!Number.isFinite(nextHeight)||nextWidth<1||nextWidth>5000||nextHeight<1||nextHeight>5000){if(commit){width.value=state.canvasWidth;height.value=state.canvasHeight;showToast('画布尺寸请输入 1–5000 之间的整数');}return;}state.canvasWidth=Math.round(nextWidth);state.canvasHeight=Math.round(nextHeight);if(locked){if(side==='width')state.canvasHeight=clampNumber(Math.round(state.canvasWidth/ratio),1,5000,state.canvasHeight);else state.canvasWidth=clampNumber(Math.round(state.canvasHeight*ratio),1,5000,state.canvasWidth);}width.value=state.canvasWidth;height.value=state.canvasHeight;ratio=state.canvasWidth/state.canvasHeight;scheduleRender();}
  function updateResolution(commit){var input=document.getElementById('resolutionDpi'),value=Number(input.value);if(!Number.isFinite(value)||value<72||value>1200){if(commit){input.value=state.resolutionDpi;showToast('分辨率请输入 72–1200 DPI');}return;}state.resolutionDpi=Math.round(value);input.value=state.resolutionDpi;}
  function reset(){var keepStickers=state.stickers,keepBackground=state.background,keepErased=state.erased;Object.assign(state,defaults);state.stickers=keepStickers;state.background=keepBackground;state.erased=keepErased;if(keepBackground){state.canvasWidth=keepBackground.naturalWidth||state.canvasWidth;state.canvasHeight=keepBackground.naturalHeight||state.canvasHeight;}ratio=1;document.getElementById('canvasWidth').value=state.canvasWidth;document.getElementById('canvasHeight').value=state.canvasHeight;document.getElementById('resolutionDpi').value=300;document.getElementById('lockRatio').checked=true;syncControlsFromState();updatePatternSelectUI();document.getElementById('customUpload').value='';document.getElementById('uploadLabel').textContent='上传自定义图案（PNG/SVG）';document.getElementById('removeCustom').hidden=true;window.App&&window.App.onReset&&window.App.onReset();scheduleRender();showToast('已恢复推荐默认参数');}
  function connectColorValues(name,value){document.getElementById(name+'Picker').style.background=value;}
  // ---- custom pattern dropdown (native <select> is ugly on mobile) ----
  var PATTERN_OPTIONS=[
    {type:'circle',name:'圆形'},{type:'star',name:'星星'},{type:'heart',name:'爱心'},
    {type:'paw',name:'猫爪'},{type:'droplet',name:'水滴'},{type:'clover',name:'四叶草'},
    {type:'cross',name:'十字架'},{type:'stripe',name:'条纹'},{type:'gingham',name:'维希格'},
    {type:'ironworkA',name:'铁艺·心卷'},{type:'ironworkB',name:'铁艺·蔓卷'},
    {type:'custom',name:'自定义图案'}
  ];
  var patternPopup=null, patternPopupOpenedAt=0, iconTileImages={};
  var ICON_COLOR='#c2687e';
  function getIconTile(type){var img=iconTileImages[type];if(img)return img.complete&&img.naturalWidth?img:null;var src=window.PatternTiles&&window.PatternTiles.sources&&window.PatternTiles.sources[type];if(!src)return null;img=new Image();img.onload=function(){updatePatternSelectUI();};img.src=src;iconTileImages[type]=img;return null;}
  function tintIconTile(img,size){var c=document.createElement('canvas');c.width=c.height=size;var x=c.getContext('2d');x.drawImage(img,0,0,size,size);x.globalCompositeOperation='source-in';x.fillStyle=ICON_COLOR;x.fillRect(0,0,size,size);return c;}
  function drawPatternIcon(canvas,type){var ctx=canvas.getContext('2d');ctx.clearRect(0,0,26,26);if(type==='stripe'){ctx.fillStyle=ICON_COLOR;[3,11,19].forEach(function(x){ctx.fillRect(x,3,4,20);});}else if(type==='gingham'){ctx.fillStyle=ICON_COLOR;ctx.globalAlpha=.5;[3,11,19].forEach(function(v){ctx.fillRect(v,3,4,20);ctx.fillRect(3,v,20,4);});ctx.globalAlpha=1;[3,11,19].forEach(function(x){[3,11,19].forEach(function(y){ctx.fillRect(x,y,4,4);});});}else if(type==='custom'){if(state.customImage){var img=state.customImage,ratio=img.naturalWidth/img.naturalHeight||1,w=ratio>=1?20:20*ratio,h=ratio>=1?20/ratio:20;ctx.drawImage(img,13-w/2,13-h/2,w,h);}else{ctx.strokeStyle=ICON_COLOR;ctx.lineWidth=1.5;ctx.setLineDash([3,3]);ctx.strokeRect(4.5,4.5,17,17);ctx.setLineDash([]);}}else if(type==='ironworkA'||type==='ironworkB'){var tile=getIconTile(type);if(tile){ctx.drawImage(tintIconTile(tile,20),3,3);}}else{(window.Patterns[type]||window.Patterns.circle)(ctx,13,13,18,ICON_COLOR);}}
  function updatePatternSelectUI(){var option=PATTERN_OPTIONS.filter(function(item){return item.type===state.patternType;})[0]||PATTERN_OPTIONS[0];document.getElementById('patternSelectName').textContent=option.name;drawPatternIcon(document.getElementById('patternSelectIcon'),option.type);}
  function closePatternPopup(){if(!patternPopup)return;patternPopup.remove();patternPopup=null;document.getElementById('patternSelectBtn').setAttribute('aria-expanded','false');document.removeEventListener('pointerdown',onPatternPopupOutside,true);document.removeEventListener('keydown',onPatternPopupKey,true);window.removeEventListener('resize',closePatternPopup);window.removeEventListener('scroll',onPatternPopupScroll,true);}
  function onPatternPopupOutside(event){if(patternPopup&&!patternPopup.contains(event.target)&&event.target.id!=='patternSelectBtn'&&!document.getElementById('patternSelectBtn').contains(event.target))closePatternPopup();}
  function onPatternPopupKey(event){if(event.key==='Escape')closePatternPopup();}
  // Mobile browsers fire a settling scroll right after the tap that opened the
  // popup; ignore scrolls for a short grace period or the popup closes instantly.
  // Scrolls that happen inside the popup itself must never close it; only a
  // page/controls scroll behind the popup should (and only after the grace period).
  function onPatternPopupScroll(event){if(patternPopup&&event.target&&(event.target===patternPopup||patternPopup.contains(event.target)))return;if(Date.now()-patternPopupOpenedAt>400)closePatternPopup();}
  function openPatternPopup(){if(patternPopup){closePatternPopup();return;}var button=document.getElementById('patternSelectBtn');button.setAttribute('aria-expanded','true');var popup=document.createElement('div');popup.className='pattern-select-popup';popup.setAttribute('role','listbox');PATTERN_OPTIONS.forEach(function(option){var item=document.createElement('button');item.type='button';item.className='ps-item'+(option.type===state.patternType?' is-selected':'');item.setAttribute('role','option');var icon=document.createElement('canvas');icon.width=icon.height=26;drawPatternIcon(icon,option.type);var label=document.createElement('span');label.textContent=option.name;item.appendChild(icon);item.appendChild(label);item.addEventListener('click',function(){if(option.type==='custom'&&!state.customImage){showToast('请先上传自定义图案');closePatternPopup();return;}state.patternType=option.type;updatePatternSelectUI();scheduleRender();closePatternPopup();});popup.appendChild(item);});document.body.appendChild(popup);patternPopup=popup;var rect=button.getBoundingClientRect(),pw=Math.max(rect.width,180),ph=Math.min(popup.scrollHeight,320);popup.style.width=pw+'px';var left=Math.max(8,Math.min(rect.left,window.innerWidth-pw-8)),top=rect.bottom+6;if(top+ph>window.innerHeight-8){top=Math.max(8,rect.top-ph-6);}popup.style.left=left+'px';popup.style.top=top+'px';document.addEventListener('pointerdown',onPatternPopupOutside,true);document.addEventListener('keydown',onPatternPopupKey,true);window.addEventListener('resize',closePatternPopup);patternPopupOpenedAt=Date.now();window.addEventListener('scroll',onPatternPopupScroll,true);}
  document.getElementById('patternSelectBtn').addEventListener('click',openPatternPopup);
  function loadFile(file){if(!file)return;if(!/^image\/(png|svg\+xml|jpeg|webp)$/.test(file.type)){showToast('暂不支持该图片格式');return;}var reader=new FileReader();reader.onload=function(){var image=new Image();image.onload=function(){state.customImage=image;state.patternType='custom';updatePatternSelectUI();document.getElementById('uploadLabel').textContent=file.name;document.getElementById('removeCustom').hidden=false;scheduleRender();showToast('自定义图案已载入');};image.onerror=function(){showToast('图案加载失败，请重新选择');};image.src=reader.result;};reader.onerror=function(){showToast('图案加载失败，请重新选择');};reader.readAsDataURL(file);}
  // Pattern/sticker/eraser pointer interactions live in js/editor.js (window.App).
  document.getElementById('canvasWidth').addEventListener('input',function(){updateCanvasSize('width',false);});document.getElementById('canvasHeight').addEventListener('input',function(){updateCanvasSize('height',false);});document.getElementById('canvasWidth').addEventListener('change',function(){updateCanvasSize('width',true);});document.getElementById('canvasHeight').addEventListener('change',function(){updateCanvasSize('height',true);});document.getElementById('resolutionDpi').addEventListener('input',function(){updateResolution(false);});document.getElementById('resolutionDpi').addEventListener('change',function(){updateResolution(true);});document.getElementById('lockRatio').addEventListener('change',function(){ratio=state.canvasWidth/state.canvasHeight;});document.getElementById('backgroundTransparent').addEventListener('change',function(){if(state.background){this.checked=false;showToast('已使用自定义背景图，透明背景暂不可用');return;}state.backgroundTransparent=this.checked;syncBackgroundTransparency();scheduleRender();});
  document.getElementById('customUpload').addEventListener('change',function(e){loadFile(e.target.files[0]);});var upload=document.getElementById('uploadArea');['dragenter','dragover'].forEach(function(type){upload.addEventListener(type,function(e){e.preventDefault();upload.classList.add('dragging');});});['dragleave','drop'].forEach(function(type){upload.addEventListener(type,function(e){e.preventDefault();upload.classList.remove('dragging');});});upload.addEventListener('drop',function(e){loadFile(e.dataTransfer.files[0]);});document.getElementById('removeCustom').addEventListener('click',function(){state.customImage=null;state.patternType='circle';updatePatternSelectUI();document.getElementById('customUpload').value='';document.getElementById('uploadLabel').textContent='上传自定义图案（PNG/SVG）';this.hidden=true;scheduleRender();});
  document.getElementById('resetButton').addEventListener('click',reset);
  // Web build: the 发小红书 action only works inside the mini-tool container
  // (window.xhs bridge). Outside it, hide the button entirely; inside the
  // container the bridge exists before page scripts run, so it stays visible.
  function syncShareVisibility(){var bridge=window.xhs&&window.xhs.miniTool;document.getElementById('shareNoteButton').hidden=!(bridge&&typeof bridge.postNote==='function');}
  syncShareVisibility();window.addEventListener('load',syncShareVisibility);
  document.getElementById('swapColors').addEventListener('click',function(){var before=window.Editor&&window.Editor.snapshotParams();var bg=state.backgroundColor;state.backgroundColor=state.patternColor;state.patternColor=bg;document.getElementById('backgroundPicker').style.background=state.backgroundColor;document.getElementById('patternPicker').style.background=state.patternColor;scheduleRender();window.Editor&&window.Editor.pushParamDirect(before);showToast('已互换背景与图案颜色');});
  document.getElementById('shareNoteButton').addEventListener('click',async function(){var bridge=window.xhs&&window.xhs.miniTool;if(!bridge||typeof bridge.postNote!=='function'){showToast('发小红书仅在小红书小工具内可用');return;}var button=this;button.disabled=true;try{var dataUri=window.PatternExport.renderDataUri(state,document.getElementById('exportFormat').value);var imageUrl=dataUri;if(typeof bridge.writeTempFile==='function'){try{var tempFile=await bridge.writeTempFile({data:dataUri});if(tempFile&&tempFile.filePath){imageUrl=tempFile.filePath;}}catch(tempError){imageUrl=dataUri;}}await bridge.postNote({mediaInfo:{image_resources:[{url:imageUrl}]}});showToast('已打开笔记发布界面');}catch(error){showToast((error&&error.errMsg)||(error&&error.message)||'发布失败，请重试');}finally{button.disabled=false;}});
  document.getElementById('exportButton').addEventListener('click',async function(){var button=this;button.classList.add('is-exporting');button.disabled=true;button.querySelector('.button-text').textContent='导出中...';try{var flattened=await window.PatternExport.exportImage(state,document.getElementById('exportFormat').value);showToast(flattened?'JPG 不支持透明背景，已使用白色底':'图片已保存');}catch(error){var bridgeActive=window.xhs&&window.xhs.miniTool;var pickerCancel=error&&error.name==='AbortError'&&!bridgeActive;if(pickerCancel){showToast('已取消导出');}else{var message=(error&&(error.errMsg||error.message))||('图片导出失败'+(error&&error.name?'（'+error.name+'）':'')+'，请重试');if(message.indexOf('auth')>=0||message.indexOf('permission')>=0||message.indexOf('denied')>=0||message.indexOf('权限')>=0){message+='（可在系统设置中允许小红书访问相册后重试）';}showToast(message);}}finally{button.classList.remove('is-exporting');button.disabled=false;button.querySelector('.button-text').textContent='导出图片';}});
  function supportsFlexGap(){var flex=document.createElement('div');flex.style.position='absolute';flex.style.visibility='hidden';flex.style.display='flex';flex.style.flexDirection='column';flex.style.rowGap='1px';flex.appendChild(document.createElement('div'));flex.appendChild(document.createElement('div'));document.body.appendChild(flex);var supported=flex.scrollHeight===1;flex.parentNode.removeChild(flex);return supported;}
  document.documentElement.classList.add(supportsFlexGap()?'supports-flex-gap':'no-flex-gap');
  connectRange('patternSizeRange','patternSize','patternSize',1,800);connectRange('gapXRange','gapX','gapX',0,800);connectRange('gapYRange','gapY','gapY',0,800);connectRange('patternAngleRange','patternAngle','patternAngle',0,360);connectRange('patternOpacityRange','patternOpacity','patternOpacity',5,100);connectRange('patternBlurRange','patternBlur','patternBlur',0,20);connectColor('background');connectColor('pattern');syncBackgroundTransparency();updatePatternSelectUI();window.PatternRenderer.onTilesLoaded=function(){scheduleRender();updatePatternSelectUI();};if(window.ResizeObserver){new ResizeObserver(scheduleRender).observe(stage);}else{window.addEventListener('resize',scheduleRender);}scheduleRender();
  // Editor module (eraser, stickers, history, background image, tabs) needs the
  // shared state/render/toast handles; it re-registers all canvas pointer logic.
  window.App={state:state,canvas:canvas,stage:stage,scheduleRender:scheduleRender,showToast:showToast,syncControlsFromState:syncControlsFromState,onReset:null};
})();
